### ISSUE TITLE
Making ng-resource-core work with angular universal (Service side rendering)

### ISSUE THREAD

**Issue by Slals** [troyanskiy/rest-core#18]
Hi,

Nice work on `ngx-resource-core`. I recently upgraded my application to use Angular Universal as I need it to be server side rendered. But `ngx-resource-core` as some issues within the server rendering process.

I wrote a workaround in order to make it work, but in the long term I think the library has to consider server side rendering. Here is the work arround :

```js
// Workarround in server.ts
global['FormData'] = require('form-data');
global['Blob'] = function Blob() {};

// express code
```

The server will now have some global references used [here](https://github.com/troyanskiy/ngx-resource-core/blob/master/src/Resource.ts#L406) for instance. Note that I "neutralized' Blob which is not a good thing, I didn't find an easy way to replace it yet.

BTW the best fix IMO would be to tell `ngx-resource-core` what part of the code is only available for browser side.

**Comment by troyanskiy** [comment]
Hi!
It's interesting.
Could you please make s small POC on GitHub for me, so I could improve that.

Thanks a lot!

**Comment by Slals** [comment]
That's not that easy unless you're willing to import some `@angular` libs (core and common essentially).

The good workaround is to detect when the server is trying to render as we know the server (NodeJS) doesn't have some browsers side globals such as `window`, `FormData`, `Blob` or `localStorage`.

Here is how it's made in Angular Universal applications :

```js
import {Inject, PLATFORM_ID} from '@angular/core';
import {isPlatformBrowser} from '@angular/common';

export class Ressource {
    constructor(@Inject(PLATFORM_ID) private platformId: Object) { }

    doSmth() {
       if (isPlatformBrowser(this.platformId)) {
           // Code that uses browser side globals
       }
    }
}
```

If you want to I can PR a change that considers this, but I'm not sure if its the good thing to do as you would have to import Angular libraries.

**Comment by jsdream** [comment]
Hi there!

Really great work on the library. Our team is also concerned with it's usage with Angular Universal server-side rendering.

We would love to know any status of this. Is anyone going to PR Angular Universal support for this awesome library?

**Comment by troyanskiy** [comment]
Hello All.
Since I'm more focused on Apps on devices I have never used Angular Universal.
You will really help me if you can create a really simple Angular Universal app which will use the resource library and post it on git or just simple zip for me.

Thank you.

**Comment by troyanskiy** [comment]
Hello to all! )
I managed to create angular universal from there's starter and defined test resource and I could not find any issue with test resource.
Could you please reproduce it with my starter which is located here https://github.com/troyanskiy/universal-resource
I gave to @jsdream and @Slaals full access to the repo, so you can implement your resources with bugs.

Thanks!

**Comment by jsdream** [comment]
Hi @troyanskiy!

Thanks for such a quick response. I've created a PR (https://github.com/troyanskiy/universal-resource/pull/1) which demonstrates issues with ngx-resource in SSR. 

The problem is that `FormData` and `Blob` do not exist in Node.js as @Slaals already mentioned.

So in this specific scenario issues are caused by this specific piece of code: https://github.com/troyanskiy/ngx-resource-core/blob/master/src/ResourceHelper.ts#L17-L23.

Not sure if there is anything else that might fail during SSR.

P.S. After some thinking over this situation I'm not really sure anymore there is anything that should be done within the library itself, but rather `FormData` and `Blob` should be polyfilled on application level?

@troyanskiy Anyway, looking forward to your thoughts.

**Comment by father-gregor** [comment]
@troyanskiy Any updates on the issue? Maybe some general approach to avoid any problems with SSR?

**Comment by troyanskiy** [comment]
@father-gregor Hello. Sorry, not yet.
I will try to find time this week.

**Comment by troyanskiy** [comment]
Hello all.
Sorry for the delayed fix.
I think I have fixed the issue. Could you please test it on your side.
Feel free to reopen the issue.
Thanks!

**Comment by jsdream** [comment]
Thanks @troyanskiy. I will report you back if I detect any other issues.

**Comment by wosevision** [comment]
Hello!

I'm still seeing this issue as of 5.4.2 – has this change made it out to the version on NPM yet or do I need to install from Git to get this fix?

I should also note that the companion library for using this with `HttpClient` (ngx-resource-handler-ngx-http) has universal issues as well – specifically, the one I ran into was an incompatibility between the `HttpResponse` interface on browser/server. The [handleResponse method](https://github.com/troyanskiy/ngx-resource-handler-ngx-http/blob/0c70226b166d8b4cbff790521d06216338b05740/src/ResourceHandlerHttpClient.ts#L105) causes an error as early as [L108](https://github.com/troyanskiy/ngx-resource-handler-ngx-http/blob/0c70226b166d8b4cbff790521d06216338b05740/src/ResourceHandlerHttpClient.ts#L108) due to the access of `response.headers`, which is undefined on the Node response (`getHeaders()` is used instead).

Have you had any interest for universal support besides what's come up here, @troyanskiy? I might be able to open up a PR on that repo if it's something you had on your roadmap.

**Comment by troyanskiy** [comment]
Hello @wosevision 

It will be nice if you can create the PR for that.

Thanks!
